### ISSUE TITLE
leadsThree.ejs: Update method and action

### ISSUE THREAD

**Issue by romebell** [molikkidd/Indy-Mo#1]
This line `method` and `action` to be updated in order for the user to search : https://github.com/molikkidd/Indy-Mo/blob/2b634d5d73bdbfe17efc41a9871efef0260e2c75/views/leadsThree.ejs#L6

```ejs
  <form class="col-6 m-2" method="POST" action="/profile/leads/ssearchLead" >
```

- [x] Update method to `POST`
- [x] Update action to `/profile/leads/ssearchLead`
- [x] Create a controller function `searchLead` that will include `searchLead` inside `req.body`
- [x] Create a `router.post('/profile/leads/searchLead')`
- [x] Then you can search your database with that `searchLead`
- [x] Get the `id`
- [x] Then `res.redirect('/profile/leads/:idx')` to a that individual lead

**Comment by molikkidd** [comment]
Thanks for your help, the suggestions worked.

**Comment by romebell** [comment]
Can you put that error here @molikkidd
